(function(){'use strict';
const $=id=>document.getElementById(id);let sb,pack,basePhotos=[],choiceSelection=new Map(),ready=[],busy=false,stopped=false,checkVersion=0;
const bucket=window.GUIDE_BUCKET||'guide-media';const status=t=>$('status').textContent=t;
const norm=s=>String(s||'').normalize('NFC').trim();
const uuid=s=>/^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/i.test(s);
function imageBytes(row){const raw=atob(row.base64),bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));if(bytes.length<500||bytes.length>6000000)throw Error('Некорректный размер фотографии');const jpg=bytes[0]===255&&bytes[1]===216&&bytes[2]===255;const png=bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71;const webp=String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP';if(!((row.mime==='image/jpeg'&&jpg)||(row.mime==='image/png'&&png)||(row.mime==='image/webp'&&webp)))throw Error('Неизвестный формат фото');return bytes;}
function validate(value){if(value.format!=='lapsha-existing-photo-pack-v1'||!Array.isArray(value.photos)||!value.photos.length||value.photos.length>200)throw Error('Выберите подготовленный файл lapsha-photos.json');const seen=new Set();for(const c of value.choices||[]){if(!uuid(c.id)||!uuid(c.category_id)||!c.name||!Array.isArray(c.options)||!c.options.length||c.options.length>10)throw Error('Некорректные варианты фото');for(const o of c.options)imageBytes(o);}
 for(const r of [...value.photos,...(value.choices||[]).map(c=>({...c,...c.options[0]}))]){if(!uuid(r.id)||!uuid(r.category_id)||!r.name||seen.has(r.id)||typeof r.base64!=='string')throw Error('Некорректная или повторная запись');seen.add(r.id);imageBytes(r);}return value;}
function choiceRows(){pack.photos=[...basePhotos,...(pack.choices||[]).flatMap(c=>{const index=choiceSelection.get(c.id);return index===undefined?[]:[{...c,...c.options[index],name:c.name,options:undefined}];})];}
function drawChoices(){const box=$('choices');box.replaceChildren();if(!pack.choices?.length)return;const heading=document.createElement('h2');heading.textContent='Уточните варианты для четырёх позиций';box.append(heading);const hint=document.createElement('p');hint.textContent='Можно оставить «Пропустить» и импортировать остальные фото. Для позиции с несколькими вкусами выберите одну бутылку для обложки.';box.append(hint);
for(const c of pack.choices){const card=document.createElement('section');card.className='notice';card.style.marginBottom='12px';const label=document.createElement('label');label.textContent=c.name;const select=document.createElement('select');select.id='choice-'+c.id;label.htmlFor=select.id;select.add(new Option('Пропустить — вариант не выбран',''));c.options.forEach((o,i)=>select.add(new Option(o.label||o.source_name,String(i))));const images=document.createElement('div');images.className='grid';for(const option of c.options){const div=document.createElement('div');const img=document.createElement('img');img.src=`data:${option.mime};base64,${option.base64}`;img.alt=option.label;img.style.cssText='width:100%;height:160px;object-fit:contain;background:#fff';const caption=document.createElement('p');caption.textContent=option.label;div.append(img,caption);images.append(div);}select.onchange=async()=>{select.value===''?choiceSelection.delete(c.id):choiceSelection.set(c.id,Number(select.value));choiceRows();try{await check();}catch(e){status(e.message);}};card.append(label,select,images);box.append(card);}}
function draw(rows){$('grid').replaceChildren();for(const row of rows){const card=document.createElement('article');card.className='card';const img=document.createElement('img');img.src=`data:${row.mime};base64,${row.base64}`;img.alt=row.name;img.loading='lazy';const section=document.createElement('section');const title=document.createElement('strong');title.textContent=row.name;const text=document.createElement('p');text.textContent=row.reason||'Готово к импорту';section.append(title,text);if(row.source_url){try{const u=new URL(row.source_url);if(u.protocol==='https:'){const a=document.createElement('a');a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Источник фото';section.append(a);}}catch{}}card.append(img,section);$('grid').append(card);}}
async function check(){const request=++checkVersion;ready=[];$('apply').disabled=true;if(!pack)return;status('Сверяем существующие записи…');const {data,error}=await sb.from('items').select('id,name,category_id,group_id,image_url').in('id',pack.photos.map(r=>r.id));if(request!==checkVersion)return;if(error)throw error;const byId=new Map(data.map(i=>[i.id,i]));for(const r of pack.photos){const i=byId.get(r.id);r.reason=!i?'Запись не найдена':norm(i.name)!==norm(r.name)||i.category_id!==r.category_id||(i.group_id||null)!==(r.group_id||null)?'Название или раздел изменились — пропуск':i.image_url?.trim()?'Фото уже заполнено — сохраняем':'Готово к импорту';if(r.reason==='Готово к импорту')ready.push({...r,snapshot:i});}draw(pack.photos);$('summary').textContent=`Готово: ${ready.length}. Пропущено: ${pack.photos.length-ready.length}. Без подтверждённого фото в пакете: ${(pack.choices||[]).length-choiceSelection.size+(pack.unresolved?.length||0)}.`;status('Проверка завершена. Посмотрите фотографии и нажмите «Импортировать фотографии».');$('apply').disabled=!ready.length;}
async function auth(){const {data,error}=await sb.auth.getSession();if(error)throw error;const signed=!!data.session;$('login').hidden=signed;$('controls').hidden=!signed;status(signed?'Вы вошли. Выберите файл lapsha-photos.json.':'Войдите тем же аккаунтом, который используете в админке.');}
try{if(!window.SUPABASE_URL||!window.SUPABASE_ANON_KEY||!window.supabase)throw Error('Не загружены настройки сайта. Откройте страницу на своём Netlify-сайте.');sb=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);auth().catch(e=>status(e.message));}catch(e){status(e.message);return;}
$('login').onsubmit=async e=>{e.preventDefault();const {error}=await sb.auth.signInWithPassword({email:window.lapshaLoginEmail($('email').value),password:$('password').value});if(error)status(error.message);else{$('password').value='';await auth();}};
$('file').onchange=async()=>{checkVersion++;pack=null;ready=[];$('choices').replaceChildren();$('apply').disabled=true;$('check').disabled=true;$('grid').replaceChildren();try{const file=$('file').files[0];if(!file)return;if(file.size>150000000)throw Error('Файл слишком большой');pack=validate(JSON.parse(await file.text()));basePhotos=[...pack.photos];choiceSelection.clear();drawChoices();$('check').disabled=false;await check();}catch(e){status(e.message);}};
$('check').onclick=()=>check().catch(e=>status(e.message));$('stop').onclick=()=>{stopped=true;$('stop').disabled=true;status('Остановимся после текущей фотографии.');};
window.addEventListener('beforeunload',e=>{if(busy){e.preventDefault();e.returnValue='';}});
$('apply').onclick=async()=>{if(busy||!ready.length)return;busy=true;stopped=false;['apply','check','file'].forEach(id=>$(id).disabled=true);$('choices').querySelectorAll('select').forEach(s=>s.disabled=true);$('stop').disabled=false;$('log').textContent='';let done=0,skipped=0,failed=0;const batch=[...ready];$('progress').max=batch.length;$('progress').value=0;
try{for(const row of batch){if(stopped)break;let path,linked=false;try{
 const {data:current,error:readError}=await sb.from('items').select('id,name,category_id,group_id,image_url').eq('id',row.id).maybeSingle();if(readError)throw readError;
 if(!current||current.image_url?.trim()||norm(current.name)!==norm(row.name)||current.category_id!==row.category_id||(current.group_id||null)!==(row.group_id||null)){skipped++;$('log').textContent+=`Пропущено: ${row.name} — запись уже изменилась.\n`;continue;}
 const extension=row.mime==='image/jpeg'?'jpg':row.mime==='image/png'?'png':'webp';path=`alcohol-auto/${row.id}/import-${crypto.randomUUID()}.${extension}`;
 status(`Загружаем ${row.name}…`);const {error:uploadError}=await sb.storage.from(bucket).upload(path,imageBytes(row),{contentType:row.mime,upsert:false,cacheControl:'31536000'});if(uploadError)throw uploadError;
 let query=sb.from('items').update({image_url:path}).eq('id',row.id).eq('name',current.name).eq('category_id',current.category_id);query=current.group_id?query.eq('group_id',current.group_id):query.is('group_id',null);query=current.image_url===null?query.is('image_url',null):query.eq('image_url',current.image_url);
 const {data,error}=await query.select('id');if(error)throw error;if(!data?.length){await sb.storage.from(bucket).remove([path]);skipped++;$('log').textContent+=`Пропущено: ${row.name} — изменено во время загрузки.\n`;continue;}linked=true;done++;$('log').textContent+=`✓ ${row.name}\n`;
 }catch(e){failed++;$('log').textContent+=`Ошибка: ${row.name}: ${e.message}\n`;/* Keep an upload on an uncertain update response: the database may reference it. */}
 finally{$('progress').value=done+skipped+failed;}}
 status(`${stopped?'Остановлено':'Готово'}. Добавлено фото: ${done}; пропущено: ${skipped}; ошибок: ${failed}. Обновите страницу меню. Повторный запуск пропустит заполненные записи.`);
}finally{busy=false;$('choices').querySelectorAll('select').forEach(s=>s.disabled=false);['check','file'].forEach(id=>$(id).disabled=false);$('stop').disabled=true;$('apply').disabled=true;ready=[];}};
})();
