(function(){'use strict';
const C=window.PosCore,$=id=>document.getElementById(id),{esc,availability,labels,when}=C;
const previewNotice=window.NoticeCenter.mount();
const sb=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY),kb=C.keyboard();
let store=null,data=null,selected=new Set(),pending=null,busy=false,toastTimer,onlySelected=false,editNews=null,publishPayload=null,draftKey=null,draftId=null,previousDraft=null;
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,6000);}
function tab(name){['stock','news','history','settings'].forEach(t=>$('tab-'+t).hidden=t!==name);document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));kb.hide();C.write('lapsha-admin-tab',name);}
function visible(){const q=C.normalize($('stockSearch').value),cat=$('stockCategory').value,status=$('stockFilter').value;return (data?.items||[]).filter(i=>{const a=availability(data,i.id),g=data.groups.find(g=>g.id===i.group_id);return (!onlySelected||selected.has(i.id))&&(!cat||i.category_id===cat)&&(!status||a.status===status)&&C.normalize(i.name+' '+(g?.title||'')+' '+a.reason).includes(q);});}
function render(){if(!data)return;const cat=$('stockCategory').value;$('stockCategory').innerHTML='<option value="">Все категории</option>'+data.categories.map(c=>`<option value="${c.id}">${esc(c.title)}</option>`).join('');$('stockCategory').value=cat;
selected=new Set([...selected].filter(id=>data.items.some(i=>i.id===id)));const list=visible();selectionUI();$('stockCount').textContent=`Показано ${list.length} из ${data.items.length}. Выбор сохраняется при смене фильтра.`;
$('metricNews').textContent=data.news.filter(activeNews).length;$('adminToday').textContent=new Date().toLocaleDateString('ru-RU',{day:'numeric',month:'long'});$('metricStop').textContent=data.items.filter(i=>availability(data,i.id).status==='stop').length;
$('stockRows').innerHTML=list.map(i=>{const a=availability(data,i.id);return `<article class="stock-row"><label><input type="checkbox" data-select="${i.id}" ${selected.has(i.id)?'checked':''} aria-label="Выбрать ${esc(i.name)}"></label><div><strong>${esc(i.name)}</strong><p class="muted">${esc(data.categories.find(c=>c.id===i.category_id)?.title)}${i.published?'':' · Черновик'}</p><span class="stock-badge ${a.status}">${labels[a.status]}</span><p>${esc(a.reason)} ${a.status==='stop'?' · В стопе с '+esc(when(a.stop_since||a.updated_at)):''}</p></div><div class="stock-actions"><button role="switch" aria-checked="${a.status==='stop'}" aria-label="Стоп: ${esc(i.name)}" class="stock-state-switch" data-change="${a.status==='stop'?'available':'stop'}" data-id="${i.id}"><i aria-hidden="true"></i>${a.status==='stop'?'Снять со стопа':'Поставить в стоп'}</button></div></article>`;}).join('')||'<p>Подходящих позиций нет.</p>';
renderNews();renderHistory();
if(pending&&pending.some(p=>availability(data,p.item_id).revision!==p.revision))$('stockStatus').textContent='Статус уже изменён на другом терминале. Закройте окно и выберите позиции заново.';
}
function setSave(message){$('saveIndicator').textContent=message;}
function connected(){if(!store)return;const fresh=store.fresh;$('connection').textContent=fresh?'Данные актуальны · изменения передаются терминалам автоматически':'Нет подтверждения связи. Изменения заблокированы до восстановления соединения.';$('connection').classList.toggle('offline',!fresh);$('lastSync').textContent=store.checked?'Проверено '+new Date(store.checked).toLocaleTimeString('ru-RU'):'Ждём данные';['bulkStop','bulkAvailable'].forEach(id=>$(id).disabled=!fresh||!selected.size||busy);$('applyStock').disabled=!fresh||busy;$('publishNews').disabled=!fresh||busy;}
function requireFresh(){if(!store?.fresh)throw Error('Нет актуального соединения. Обновите данные и повторите действие.');}
function prepare(ids,status){try{if(busy)return;requireFresh();if(!ids.length)throw Error('Сначала выберите позиции.');if(ids.length>200)throw Error('За один раз можно изменить до 200 позиций.');pending=ids.map(id=>({item_id:id,status,revision:availability(data,id).revision}));$('stockDialogTitle').textContent=labels[status]+' · '+ids.length;$('changeNames').textContent=ids.map(id=>data.items.find(i=>i.id===id)?.name).join(', ');$('changeFields').hidden=status==='available';$('reason').value=status==='stop'?'Закончился':'';$('stockStatus').textContent='';kb.hide();$('stockDialog').showModal();}catch(e){toast(e.message);}}
$('closeStock').onclick=()=>{if(!busy)$('stockDialog').close();};$('stockDialog').addEventListener('cancel',e=>{if(busy)e.preventDefault();});$('stockDialog').addEventListener('close',()=>pending=null);
$('applyStock').onclick=async()=>{if(busy||!pending)return;busy=true;setSave('Сохраняем стоп-лист…');$('stockStatus').textContent='Сохраняем…';$('applyStock').disabled=true;try{requireFresh();const changes=pending.map(p=>({...p,reason:$('reason').value,quantity:null,expected_at:null}));const result=await sb.rpc('pos_set_availability',{p_changes:changes});if(result.error)throw result.error;$('stockDialog').close();selected.clear();await store.sync();setSave('Стоп-лист сохранён · '+new Date().toLocaleTimeString('ru-RU'));toast('Стоп-лист сохранён.');}catch(e){setSave('Стоп-лист не сохранён — проверьте сообщение');$('stockStatus').textContent='Не сохранено: '+e.message+' При конфликте закройте окно и выберите позиции заново.';await store.sync();}finally{busy=false;connected();}};
$('stockSearch').oninput=render;$('stockCategory').onchange=render;$('stockFilter').onchange=render;$('selectVisible').onclick=()=>{visible().forEach(i=>selected.add(i.id));render();};$('clearSelection').onclick=()=>{selected.clear();onlySelected=false;render();};[['bulkStop','stop'],['bulkAvailable','available']].forEach(([id,s])=>$(id).onclick=()=>prepare([...selected],s));$('refresh').onclick=()=>store?.sync();
document.addEventListener('change',e=>{if(e.target.dataset.select){e.target.checked?selected.add(e.target.dataset.select):selected.delete(e.target.dataset.select);if(onlySelected)render();else selectionUI();}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab)tab(b.dataset.tab);if(b.hasAttribute('data-stock-segment')){$('stockFilter').value=b.dataset.stockSegment;render();}if(b.dataset.editNews)editMessage(b.dataset.editNews,false);if(b.dataset.copyNews)editMessage(b.dataset.copyNews,true);if(b.dataset.status){tab('stock');$('stockFilter').value=b.dataset.status;render();}if(b.dataset.change)prepare([b.dataset.id],b.dataset.change);if(b.dataset.hideNews){if(busy)return;busy=true;try{requireFresh();const n=data.news.find(n=>n.id===b.dataset.hideNews);const r=await sb.from('news').update({published:false}).eq('id',n.id).eq('updated_at',n.updated_at).select('id');if(r.error)throw r.error;if(!r.data.length)throw Error('Сообщение уже изменено. Проверьте свежие данные.');setSave('Сообщение снято с публикации');toast('Сообщение снято с публикации.');}catch(e){toast(e.message);}finally{busy=false;await store.sync();}}});
const templates=[['Стоп-лист','Проверьте стоп-лист','Перед приёмом заказа проверьте актуальное наличие напитков.','important'],['Брифинг','Брифинг смены','Подойдите к администратору для короткого брифинга.','important'],['Рекомендация','Рекомендация гостю','Уточняйте предпочтения гостя перед рекомендацией напитка.','normal'],['Аллергены','Проверка состава','При вопросах об аллергенах уточняйте состав у ответственного сотрудника.','important'],['Тесты','Повторение барного меню','Откройте раздел тестов и повторите барное меню перед сменой.','normal'],['Передача смены','Передача смены','Передайте следующей смене актуальный стоп-лист и важные сообщения.','normal']];
$('newsTemplates').innerHTML=templates.map((t,i)=>`<button type="button" data-template="${i}">${t[0]}</button>`).join('');
function formValues(){return {title:$('newsTitle').value,message:$('newsMessage').value,priority:$('newsPriority').value,duration:$('newsDuration').value,pinned:$('newsPinned').checked,edit:editNews,id:draftId};}
function applyDraft(d){editNews=d?.edit||null;draftId=d?.id||crypto.randomUUID();$('newsTitle').value=d?.title||'';$('newsMessage').value=d?.message||'';$('newsPriority').value=d?.priority||'normal';$('newsDuration').value=d?.duration||'';$('newsPinned').checked=!!d?.pinned;preview(false);}
function persistDraft(){if(!draftKey)return;try{localStorage.setItem(draftKey,JSON.stringify(formValues()));$('draftStatus').textContent='Черновик сохранён на этом устройстве · '+new Date().toLocaleTimeString('ru-RU');}catch{$('draftStatus').textContent='Не удалось сохранить локальный черновик. Не закрывайте страницу до публикации.';}}
function preview(persist=true){$('newsPreview').innerHTML=`<small>Предпросмотр · ${esc($('newsPriority').selectedOptions[0].textContent)}</small><h3>${esc($('newsTitle').value||'Сообщение смены')}</h3><p>${esc($('newsMessage').value).replace(/\n/g,'<br>')}</p>`;$('newsEditBanner').hidden=!editNews;$('newsEditBanner').textContent=editNews?'Редактирование опубликованного сообщения. Сохранение отправит обновление.':'';$('publishNews').textContent=editNews?'Проверить изменения':'Проверить и опубликовать';if(persist)persistDraft();}
$('newsForm').oninput=()=>preview();
function backupDraft(){const d=formValues();if(d.message||d.title){previousDraft=d;if(draftKey)C.write(draftKey+':previous',d);$('restoreDraft').hidden=false;}}
$('newsTemplates').onclick=e=>{const b=e.target.closest('[data-template]');if(!b)return;backupDraft();editNews=null;draftId=crypto.randomUUID();const t=templates[Number(b.dataset.template)];$('newsTitle').value=t[1];$('newsMessage').value=t[2];$('newsPriority').value=t[3];$('newsDuration').value='12';preview();};
$('clearDraft').onclick=()=>{backupDraft();applyDraft(null);persistDraft();$('newsStatus').textContent='Новый черновик. Предыдущий можно восстановить.';};
$('restoreDraft').onclick=()=>{if(!previousDraft)return;const current=formValues(),old=previousDraft;applyDraft(old);previousDraft=current;C.write(draftKey+':previous',current);persistDraft();};
function editMessage(id,copy){const n=data.news.find(n=>n.id===id);if(!n)return;backupDraft();applyDraft({title:n.title,message:n.message,priority:n.priority,pinned:n.pinned,duration:copy?'12':'keep',id:copy?crypto.randomUUID():n.id,edit:copy?null:{id:n.id,updated_at:n.updated_at,expires_at:n.expires_at}});persistDraft();tab('news');$('newsForm').scrollIntoView({behavior:'smooth',block:'start'});}
$('newsForm').onsubmit=e=>{e.preventDefault();if(busy)return;try{requireFresh();const message=$('newsMessage').value.trim();if(!message)throw Error('Добавьте текст сообщения.');draftId=draftId||crypto.randomUUID();publishPayload={id:editNews?.id||draftId,title:$('newsTitle').value.trim(),message,priority:$('newsPriority').value,pinned:$('newsPinned').checked,published:true,expires_at:$('newsDuration').value==='keep'?(editNews?.expires_at||null):$('newsDuration').value?new Date(Date.now()+Number($('newsDuration').value)*3600000).toISOString():null};$('publishTitle').textContent=editNews?'Проверить изменения':'Проверить сообщение';$('publishSummary').textContent=publishPayload.title+'\n\n'+message+'\n\n'+$('newsPriority').selectedOptions[0].textContent+' · '+(publishPayload.pinned?'Закреплено':'Без закрепления')+'\n'+(publishPayload.expires_at?'До '+when(publishPayload.expires_at):'До ручного снятия');$('publishError').textContent='';kb.hide();$('publishDialog').showModal();}catch(e){$('newsStatus').textContent=e.message;}};
$('previewNotice').onclick=()=>{if(publishPayload)previewNotice.push([{id:'preview-'+Date.now(),kind:'news',title:publishPayload.title||'Сообщение смены',message:publishPayload.message,status:publishPayload.priority}]);};
$('closePublish').onclick=()=>{if(!busy)$('publishDialog').close();};$('publishDialog').addEventListener('cancel',e=>{if(busy)e.preventDefault();});
$('confirmPublish').onclick=async()=>{if(busy||!publishPayload)return;busy=true;$('confirmPublish').disabled=true;setSave('Сохраняем сообщение…');try{requireFresh();let r;if(editNews){const {id,...patch}=publishPayload;r=await sb.from('news').update(patch).eq('id',id).eq('updated_at',editNews.updated_at).select('id');if(!r.error&&!r.data.length)throw Error('Сообщение уже изменено. Закройте окно и откройте свежую версию из списка.');}else{r=await sb.from('news').insert(publishPayload);if(r.error?.code==='23505'){const existing=await sb.from('news').select('*').eq('id',publishPayload.id).single();const equal=!existing.error&&['title','message','priority','pinned','published'].every(k=>existing.data[k]===publishPayload[k])&&Date.parse(existing.data.expires_at||0)===Date.parse(publishPayload.expires_at||0);if(equal)r={error:null};}}if(r.error)throw r.error;$('publishDialog').close();applyDraft(null);persistDraft();setSave('Сообщение сохранено · '+new Date().toLocaleTimeString('ru-RU'));$('newsStatus').textContent='Сохранено. Официанты получат обновление при соединении.';await store.sync();}catch(e){setSave('Результат сохранения требует проверки');$('publishError').textContent='Не подтверждено: '+e.message+' При потере связи проверьте список сообщений перед повтором.';await store.sync();}finally{busy=false;$('confirmPublish').disabled=false;connected();}};
function activeNews(n){return n.published&&(!n.expires_at||Date.parse(n.expires_at)>Date.now());}
function renderNews(){if(!data)return;const q=C.normalize($('newsSearch').value),filter=$('newsFilter').value;const rows=data.news.filter(n=>C.normalize(n.title+' '+n.message).includes(q)&&(filter==='all'||(filter==='active'?activeNews(n):!activeNews(n))));$('adminNews').innerHTML=rows.map(n=>`<article class="admin-news-row"><div><strong>${esc(n.title||'Сообщение')}</strong><p>${esc(n.message)}</p><small>${activeNews(n)?'Активно':n.published?'Срок истёк':'Снято'}${n.pinned?' · Закреплено':''}${n.expires_at?' · До '+esc(when(n.expires_at)):''}</small></div><div class="admin-news-tools"><button data-edit-news="${n.id}">Изменить</button><button data-copy-news="${n.id}">Копировать</button>${activeNews(n)?`<button data-hide-news="${n.id}">Снять</button>`:''}</div></article>`).join('')||'<div class="admin-empty">Подходящих сообщений нет.</div>';}
function renderHistory(){if(!data)return;const q=C.normalize($('historySearch').value),kind=$('historyKind').value,period=$('historyPeriod').value;let since=0;if(period==='day')since=Date.now()-86400000;if(period==='today'){const today=new Date();today.setHours(0,0,0,0);since=today.getTime();}const rows=data.events.filter(e=>(!kind||e.kind===kind)&&Date.parse(e.created_at)>=since&&C.normalize(e.title+' '+e.message).includes(q));$('historyRows').innerHTML=rows.map(e=>`<article class="admin-news-row"><div><small>${esc(when(e.created_at))} · ${e.kind==='news'?'Сообщение':'Стоп-лист'}</small><strong>${esc(e.title)}</strong><p>${esc(e.message)}</p></div></article>`).join('')||'<div class="admin-empty">В последних 100 событиях совпадений нет.</div>';}
['newsSearch','newsFilter'].forEach(id=>$(id).addEventListener('input',renderNews));['historySearch','historyKind','historyPeriod'].forEach(id=>$(id).addEventListener('input',renderHistory));
function selectionUI(){$('selectedCount').textContent='Выбрано: '+selected.size;document.querySelector('.bulk-bar').classList.toggle('has-selection',!!selected.size);$('selectedNames').textContent=[...selected].map(id=>data?.items.find(i=>i.id===id)?.name).filter(Boolean).join(' · ');$('reviewSelected').textContent=onlySelected?'Показать все':'Посмотреть выбранные';document.querySelectorAll('[data-stock-segment]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.stockSegment===$('stockFilter').value));connected();}
$('resetStock').onclick=()=>{$('stockSearch').value='';$('stockCategory').value='';$('stockFilter').value='';onlySelected=false;render();};$('reviewSelected').onclick=()=>{onlySelected=!onlySelected;render();};
$('copyStop').onclick=async()=>{if(!data)return;const rows=data.items.filter(i=>availability(data,i.id).status==='stop').map(i=>{const a=availability(data,i.id);return i.name+' — '+(a.reason||'СТОП')+' · с '+when(a.stop_since||a.updated_at);});try{await navigator.clipboard.writeText('Стоп-лист · '+new Date().toLocaleString('ru-RU')+'\n'+(rows.join('\n')||'Стоп-лист пуст'));toast('Стоп-лист скопирован.');}catch{toast('Копирование недоступно. Используйте скачивание CSV.');}};
$('exportStop').onclick=()=>{if(!data)return;const cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const rows=[['Название','Статус','Причина','В стопе с'],...data.items.filter(i=>availability(data,i.id).status!=='available').map(i=>{const a=availability(data,i.id);return[i.name,labels[a.status],a.reason,when(a.stop_since||a.updated_at)];})];const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(cell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='lapsha-stop-list.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('printStop').onclick=()=>{tab('stock');$('stockFilter').value='stop';$('stockSearch').value='';$('stockCategory').value='';render();window.print();};
function session(s){if(store){store.stop();store=null;}data=null;selected.clear();onlySelected=false;$('adminDock').hidden=!s;$('adminTop').hidden=!s;$('workspace').hidden=!s;$('logout').hidden=!s;$('login').hidden=!!s;if(!s){$('connection').textContent='Войдите с существующей учётной записью администратора.';return;}draftKey='lapsha-admin-draft:'+SUPABASE_URL+':'+s.user.id;applyDraft(C.read(draftKey,null));previousDraft=C.read(draftKey+':previous',null);$('restoreDraft').hidden=!previousDraft;const last=C.read('lapsha-admin-tab','stock');tab(['stock','news','history','settings'].includes(last)?last:'stock');store=C.createStore(sb,true);store.on('data',e=>{data=e.data;render();});store.on('connection',connected);store.start();}
$('login').onsubmit=async e=>{e.preventDefault();const button=$('login').querySelector('button');button.disabled=true;try{const r=await sb.auth.signInWithPassword({email:window.lapshaLoginEmail($('email').value),password:$('password').value});if(r.error)throw r.error;$('password').value='';kb.hide();}catch(e){$('loginError').textContent=e.message;}finally{button.disabled=false;}};$('logout').onclick=async()=>{if(busy){toast('Дождитесь завершения сохранения.');return;}const r=await sb.auth.signOut();if(r.error)toast(r.error.message);};
document.documentElement.dataset.theme=C.read('lapsha-pos-theme','dark');$('adminTheme').checked=document.documentElement.dataset.theme==='light';$('adminTheme').onchange=()=>{const t=$('adminTheme').checked?'light':'dark';document.documentElement.dataset.theme=t;C.write('lapsha-pos-theme',t);};$('showPassword').onchange=()=>$('password').type=$('showPassword').checked?'text':'password';$('adminCompact').checked=C.read('lapsha-admin-compact',false);function compact(){document.body.classList.toggle('admin-density-compact',$('adminCompact').checked);C.write('lapsha-admin-compact',$('adminCompact').checked);}compact();$('adminCompact').onchange=compact;$('adminKeyboard').checked=C.read('lapsha-pos-keyboard',true);function keyboardPref(){C.write('lapsha-pos-keyboard',$('adminKeyboard').checked);document.querySelectorAll('[data-pos-keyboard]').forEach(i=>i.inputMode=$('adminKeyboard').checked?'none':'text');kb.hide();}keyboardPref();$('adminKeyboard').onchange=keyboardPref;$('adminTop').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});$('adminFullscreen').onclick=async()=>{try{document.fullscreenElement?await document.exitFullscreen():await document.documentElement.requestFullscreen();}catch{toast('Полноэкранный режим недоступен.');}};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'&&!$('tab-news').hidden&&!$('publishDialog').open){e.preventDefault();$('newsForm').requestSubmit();}});sb.auth.onAuthStateChange((event,s)=>{if(['INITIAL_SESSION','SIGNED_IN','SIGNED_OUT'].includes(event))session(s);});setInterval(connected,10000);
})();
