(function(){'use strict';
const C=window.PosCore,$=id=>document.getElementById(id),{esc,availability,labels,when}=C;
const sb=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY),kb=C.keyboard();
let store=null,data=null,selected=new Set(),pending=null,busy=false,toastTimer;
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,6000);}
function tab(name){['stock','news','history'].forEach(t=>$('tab-'+t).hidden=t!==name);document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));kb.hide();}
function visible(){const q=C.normalize($('stockSearch').value),cat=$('stockCategory').value,status=$('stockFilter').value;return (data?.items||[]).filter(i=>{const a=availability(data,i.id),g=data.groups.find(g=>g.id===i.group_id);return (!cat||i.category_id===cat)&&(!status||a.status===status)&&C.normalize(i.name+' '+(g?.title||'')).includes(q);});}
function render(){if(!data)return;const cat=$('stockCategory').value;$('stockCategory').innerHTML='<option value="">Все категории</option>'+data.categories.map(c=>`<option value="${c.id}">${esc(c.title)}</option>`).join('');$('stockCategory').value=cat;
selected=new Set([...selected].filter(id=>data.items.some(i=>i.id===id)));const list=visible();$('selectedCount').textContent='Выбрано: '+selected.size;$('stockCount').textContent=`Показано ${list.length} из ${data.items.length}. Выбор сохраняется при смене фильтра.`;
$('metricStop').textContent=data.items.filter(i=>availability(data,i.id).status==='stop').length;
$('stockRows').innerHTML=list.map(i=>{const a=availability(data,i.id);return `<article class="stock-row"><label><input type="checkbox" data-select="${i.id}" ${selected.has(i.id)?'checked':''} aria-label="Выбрать ${esc(i.name)}"></label><div><strong>${esc(i.name)}</strong><p class="muted">${esc(data.categories.find(c=>c.id===i.category_id)?.title)}${i.published?'':' · Черновик'}</p><span class="stock-badge ${a.status}">${labels[a.status]}</span><p>${esc(a.reason)} ${a.status==='stop'?' · В стопе с '+esc(when(a.stop_since||a.updated_at)):''}</p></div><div class="stock-actions"><button data-change="stop" data-id="${i.id}" class="danger-button">СТОП</button><button data-change="available" data-id="${i.id}" class="success-button">В наличии</button></div></article>`;}).join('')||'<p>Подходящих позиций нет.</p>';
$('adminNews').innerHTML=data.news.map(n=>`<article class="admin-news-row"><div><strong>${esc(n.title||'Сообщение')}</strong><p>${esc(n.message)}</p><small>${n.published?'Опубликовано':'Снято с публикации'}${n.expires_at?' · До '+esc(when(n.expires_at)):''}</small></div>${n.published?`<button data-hide-news="${n.id}">Снять с публикации</button>`:''}</article>`).join('')||'<p>Сообщений пока нет.</p>';
$('historyRows').innerHTML=data.events.map(e=>`<article class="admin-news-row"><div><small>${esc(when(e.created_at))}</small><strong>${esc(e.title)}</strong><p>${esc(e.message)}</p></div></article>`).join('')||'<p>Изменений пока нет.</p>';
if(pending&&pending.some(p=>availability(data,p.item_id).revision!==p.revision))$('stockStatus').textContent='Статус уже изменён на другом терминале. Закройте окно и выберите позиции заново.';
}
function connected(){if(!store)return;const fresh=store.fresh;$('connection').textContent=fresh?'Данные актуальны · изменения передаются терминалам автоматически':'Нет подтверждения связи. Изменения заблокированы до восстановления соединения.';$('connection').classList.toggle('offline',!fresh);}
function requireFresh(){if(!store?.fresh)throw Error('Нет актуального соединения. Обновите данные и повторите действие.');}
function prepare(ids,status){try{requireFresh();if(!ids.length)throw Error('Сначала выберите позиции.');if(ids.length>200)throw Error('За один раз можно изменить до 200 позиций.');pending=ids.map(id=>({item_id:id,status,revision:availability(data,id).revision}));$('stockDialogTitle').textContent=labels[status]+' · '+ids.length;$('changeNames').textContent=ids.map(id=>data.items.find(i=>i.id===id)?.name).join(', ');$('changeFields').hidden=status==='available';$('reason').value=status==='stop'?'Закончился':'';$('stockStatus').textContent='';kb.hide();$('stockDialog').showModal();}catch(e){toast(e.message);}}
$('closeStock').onclick=()=>{if(!busy)$('stockDialog').close();};$('stockDialog').addEventListener('cancel',e=>{if(busy)e.preventDefault();});$('stockDialog').addEventListener('close',()=>pending=null);
$('applyStock').onclick=async()=>{if(busy||!pending)return;busy=true;$('applyStock').disabled=true;try{requireFresh();const changes=pending.map(p=>({...p,reason:$('reason').value,quantity:null,expected_at:null}));const result=await sb.rpc('pos_set_availability',{p_changes:changes});if(result.error)throw result.error;$('stockDialog').close();selected.clear();await store.sync();toast('Наличие сохранено. Терминалы получат обновление.');}catch(e){$('stockStatus').textContent='Не сохранено: '+e.message+' При конфликте закройте окно и выберите позиции заново.';await store.sync();}finally{busy=false;$('applyStock').disabled=false;}};
$('stockSearch').oninput=render;$('stockCategory').onchange=render;$('stockFilter').onchange=render;$('selectVisible').onclick=()=>{visible().forEach(i=>selected.add(i.id));render();};$('clearSelection').onclick=()=>{selected.clear();render();};[['bulkStop','stop'],['bulkAvailable','available']].forEach(([id,s])=>$(id).onclick=()=>prepare([...selected],s));$('refresh').onclick=()=>store?.sync();
document.addEventListener('change',e=>{if(e.target.dataset.select){e.target.checked?selected.add(e.target.dataset.select):selected.delete(e.target.dataset.select);$('selectedCount').textContent='Выбрано: '+selected.size;}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab)tab(b.dataset.tab);if(b.dataset.status){tab('stock');$('stockFilter').value=b.dataset.status;render();}if(b.dataset.change)prepare([b.dataset.id],b.dataset.change);if(b.dataset.hideNews){if(busy)return;busy=true;try{requireFresh();const n=data.news.find(n=>n.id===b.dataset.hideNews);const r=await sb.from('news').update({published:false}).eq('id',n.id).eq('updated_at',n.updated_at).select('id');if(r.error)throw r.error;if(!r.data.length)throw Error('Сообщение уже изменено. Проверьте свежие данные.');toast('Сообщение снято с публикации.');}catch(e){toast(e.message);}finally{busy=false;await store.sync();}}});
const templates=[['Стоп-лист','Проверьте стоп-лист','Перед приёмом заказа проверьте актуальное наличие напитков.','important'],['Брифинг','Брифинг смены','Подойдите к администратору для короткого брифинга.','important'],['Рекомендация','Рекомендация гостю','Уточняйте предпочтения гостя перед рекомендацией напитка.','normal'],['Аллергены','Проверка состава','При вопросах об аллергенах уточняйте состав у ответственного сотрудника.','important'],['Тесты','Повторение барного меню','Откройте раздел тестов и повторите барное меню перед сменой.','normal'],['Передача смены','Передача смены','Передайте следующей смене актуальный стоп-лист и важные сообщения.','normal']];
$('newsTemplates').innerHTML=templates.map((t,i)=>`<button type="button" data-template="${i}">${t[0]}</button>`).join('');$('newsTemplates').onclick=e=>{const b=e.target.closest('[data-template]');if(!b)return;const t=templates[Number(b.dataset.template)];$('newsTitle').value=t[1];$('newsMessage').value=t[2];$('newsPriority').value=t[3];$('newsDuration').value='12';preview();};function preview(){$('newsPreview').innerHTML=`<small>Предпросмотр · ${esc($('newsPriority').selectedOptions[0].textContent)}</small><h3>${esc($('newsTitle').value||'Сообщение смены')}</h3><p>${esc($('newsMessage').value).replace(/\n/g,'<br>')}</p>`;}$('newsForm').oninput=preview;preview();
$('newsForm').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;$('publishNews').disabled=true;try{requireFresh();const message=$('newsMessage').value.trim();if(!message)throw Error('Добавьте текст сообщения.');const r=await sb.from('news').insert({title:$('newsTitle').value.trim(),message,priority:$('newsPriority').value,pinned:$('newsPinned').value==='yes',published:true,expires_at:$('newsDuration').value?new Date(Date.now()+Number($('newsDuration').value)*3600000).toISOString():null});if(r.error)throw r.error;$('newsForm').reset();preview();$('newsStatus').textContent='Опубликовано. Сообщение отправлено на экраны официантов.';await store.sync();}catch(e){$('newsStatus').textContent='Не опубликовано: '+e.message;}finally{busy=false;$('publishNews').disabled=false;}};
$('exportStop').onclick=()=>{if(!data)return;const cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const rows=[['Название','Статус','Причина','В стопе с'],...data.items.filter(i=>availability(data,i.id).status!=='available').map(i=>{const a=availability(data,i.id);return[i.name,labels[a.status],a.reason,when(a.stop_since||a.updated_at)];})];const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(cell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='lapsha-stop-list.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('printStop').onclick=()=>{tab('stock');$('stockFilter').value='stop';$('stockSearch').value='';$('stockCategory').value='';render();window.print();};
function session(s){if(store){store.stop();store=null;}data=null;selected.clear();$('workspace').hidden=!s;$('logout').hidden=!s;$('login').hidden=!!s;if(!s){$('connection').textContent='Войдите с существующей учётной записью администратора.';return;}store=C.createStore(sb,true);store.on('data',e=>{data=e.data;render();});store.on('connection',connected);store.start();}
$('login').onsubmit=async e=>{e.preventDefault();const button=$('login').querySelector('button');button.disabled=true;try{const r=await sb.auth.signInWithPassword({email:window.lapshaLoginEmail($('email').value),password:$('password').value});if(r.error)throw r.error;$('password').value='';kb.hide();}catch(e){$('loginError').textContent=e.message;}finally{button.disabled=false;}};$('logout').onclick=async()=>{const r=await sb.auth.signOut();if(r.error)toast(r.error.message);};
document.documentElement.dataset.theme=C.read('lapsha-pos-theme','dark');$('adminTheme').onclick=()=>{const t=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=t;C.write('lapsha-pos-theme',t);};sb.auth.onAuthStateChange((event,s)=>{if(['INITIAL_SESSION','SIGNED_IN','SIGNED_OUT'].includes(event))session(s);});setInterval(connected,10000);
})();
